server:
  port: 8080

spring:
  application:
    name: light-mes-backend
  datasource:
    url: jdbc:mysql://localhost:3306/light_mes?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: "000518"
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

mes:
  jwt:
    secret: 04aff72d4a76a807f1e8f9c2114fb51c422b26a4f89c4a019474a22b77af6fd0b89b7b565579799ae0bd80377a9239ffff6770163d0f0990ccd8282dd43f6b41
    expire-hours: 24
  panelx:
    base-url: https://demo.kwaidoo.com/VF_DEV/
    bus-domain-code: SdkTest
    app-code: SdkTest
    username: admin
    password: "123456"
    panel-map:
      MANU_ORDER: SdkTest_IML_00002
